name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ["v1.x", "canary"]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Run lint
        run: deno lint

      - name: Run tests
        run: deno test --coverage=./coverage && deno coverage ./coverage --lcov > ./coverage/cov_profile.lcov

      - name: sending coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/cov_profile.lcov
